### ISSUE TITLE
[FR] Simple node link to file

### ISSUE THREAD

**Issue by phortx** [Developer-Mike/obsidian-advanced-canvas#172]
Hi,

I'd love to have a simple text node that acts as a link and opens a specific markdown file on click. I know you can add files directly, but those look different and lack of customization options.

**Comment by Developer-Mike** [comment]
Thank you for the FR. Why doesn't a text node with a `[[wikilink]]` work in your case?

**Comment by phortx** [comment]
Hi @Developer-Mike !

Lol, I didn't realize this is possible. It works, thanks! However with a downside: You have to click twice and you have to click on the text instead of the whole node. But this is fine fore me :) 

Feel free to leave this request open, when you think this would be a good addition to the plugin, otherwise you may close it.

Thanks!

**Comment by Developer-Mike** [comment]
To fix the double click-requirement, you can add a CSS snippet:
```css
.canvas-node-content:has(.markdown-preview-view > .markdown-preview-section > div.el-p:nth-child(2):last-child > p > a) + .canvas-node-content-blocker {
  display: none;
}
```

But this will also change it so that you only need to click once to edit the text content of the node.
Because of this "fix", I'll close this issue for now.
