### ISSUE TITLE
[FR] checkmark/emoji to validate status of cards

### ISSUE THREAD

**Issue by Jopp-gh** [Developer-Mike/obsidian-advanced-canvas#177]
### Problem
By default and without plugins, we can't fold/unfold or validate canvas cards (like on a mindmap).

### Solution
I'd appreciate if your plugin could add a toggle checkmark/space to add a custom emoji to the upper right corner of each card. 
This way, we could see at a glace if topics need attention or are already done/completed/read.

### Workaround
Currently I add a h3 emoji to the top of my documents, but I'd prefer to see these symbols/emojis only on Obsidians canvas and not, in my original note.

**Comment by Developer-Mike** [comment]
Why don't you use the coloring feature?

**Comment by Developer-Mike** [comment]
Take a look at this [custom style](https://github.com/Developer-Mike/obsidian-advanced-canvas/blob/main/README.md#custom-styles) I've just created:

data.json
```json
"customNodeStyleAttributes": [
    {
      "datasetKey": "validationState",
      "label": "Validation State",
      "options": [
          {
              "icon": "circle-help",
              "label": "Stateless",
              "value": null
          },
          {
              "icon": "circle-check",
              "label": "Approved",
              "value": "approved"
          },
          {
              "icon": "circle-dot",
              "label": "Pending",
              "value": "pending"
          },
          {
              "icon": "circle-x",
              "label": "Rejected",
              "value": "rejected"
          }
      ]   
    }
  ]
```

CSS Snippet
```css
.canvas-node[data-validation-state] .canvas-node-content::after {
  content: "";

  position: absolute;
  top: 10px;
  right: 10px;

  font-size: 1em;
}

.canvas-node[data-validation-state="approved"] .canvas-node-content::after {
  content: "✔️";
}

.canvas-node[data-validation-state="pending"] .canvas-node-content::after {
  content: "⏳";
}

.canvas-node[data-validation-state="rejected"] .canvas-node-content::after {
  content: "❌";
}
```

![Image](https://github.com/user-attachments/assets/8b1aad4d-5060-48db-aa8f-877f4d702642)

This should be a good starting point for what you're trying to achieve. I won't add it to the plugin tho bc I think it's a niche usecase.
