### ISSUE TITLE
[FR] Option to hide grid in read-only mode

### ISSUE THREAD

**Issue by Anarchtism** [Developer-Mike/obsidian-advanced-canvas#189]
I use the CSS snippet
```CSS
svg.canvas-background {
    display: none !important;
}
```
to hide the grid in Canvas, but there was an option in Advanced Canvas to hide the grid in read-only mode that'd be neat and require less fiddling in Obsidian's Appearance settings.
