### ISSUE TITLE
[BUG]When adding a custom style the option to select a color from the color wheel disappears

### ISSUE THREAD

**Issue by anuzk13** [Developer-Mike/obsidian-advanced-canvas#206]
I followed the instructions to add custom style here: https://github.com/Developer-Mike/obsidian-advanced-canvas/issues 

After I apply one of the options to a node the option to select a color using the color wheel disappears (only default colors are available)

I added an option to create a solid background with this code:

``` css
/* @advanced-canvas-node-style
key: validation-state
label: Validation State
options:
  -
    label: Default
    value: null
    icon: pencil-off

  -
    label: Solid
    value: solid
    icon: paint-bucket
*/

.canvas-node[data-validation-state="solid"] .canvas-node-content {
  background-color: rgba(var(--canvas-color), 1.0);
}
```

But then the option to select the background using the color wheel disappears:
<img width="373" alt="Image" src="https://github.com/user-attachments/assets/a15165b6-c93c-4bbc-b1a4-af59503403ed" />

It is still available for non modified nodes:

<img width="329" alt="Image" src="https://github.com/user-attachments/assets/c4b0006a-e693-4b69-a88b-dbf1604bc096" />
