### ISSUE TITLE
[FR] The thickness of the Edge can be adjusted, and the shape of the Edge can be controlled

### ISSUE THREAD

**Issue by JingofXin** [Developer-Mike/obsidian-advanced-canvas#87]
This plugin is great! The native Obsidian has a problem that is not very friendly: when the Node or group is very large (or the positions of the two Nodes are not suitable), the Edge line will not only look very thin, but also look ugly. I hope this plugin can make up for this shortcoming.
Specifically, there are more settings for Edge:
1. The thickness of the Edge can be adjusted. I hope to give some pre-made thickness options, or set the thickness by numbers.
2. the shape of the Edge can be controlled. I hope to add control points or Bezier curves to control the shape of the Edge.

**Comment by Developer-Mike** [comment]
1. To fix this issue, you can easily add a new style attribute ([Tutorial](https://github.com/Developer-Mike/obsidian-advanced-canvas?tab=readme-ov-file#custom-styles)).
The css would look something like this:
```css
.canvas-edges .canvas-display-path[data-<PROPERTY-NAME>="<VALUE>"] {
  /* 24px is the default value */
  stroke-width: calc(24px * var(--zoom-multiplier));
}
```

2. Edge path anchors are a planned feature. But it will take some time before it gets released. ([Here](https://github.com/Developer-Mike/obsidian-advanced-canvas/tree/edge-path-anchors) is the branch)

**Comment by JingofXin** [comment]
Thanks a lot, but I have a problem. I followed the example setup, but the color background doesn't take effect.
- datajson:
![image](https://github.com/user-attachments/assets/0d45e413-386b-4d51-96fa-a4984715a001)

- snippets:
```css
.canvas-node[data-datasetKey="rainy"] {
  background-color: #df3535;
}
```
and I enable the snippet in vault:
![image](https://github.com/user-attachments/assets/f9c615a1-f0d0-4f16-8969-7d20215670ec)

result: the color background doesn't take effect
![image](https://github.com/user-attachments/assets/f614934a-8332-4e62-8f8b-ed607b625ee9)
